name: layout
description: >-
  Sample app from "Building Layouts", https://docs.flutter.dev/ui/layout.
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

dev_dependencies:
  example_utils:
    path: ../../example_utils
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
